#!/bin/bash

# make reloading settings a bit simpler
alias reload='source ~/.bash_profile'

# directory traversal, up 'n' folders
alias ..="cd .."
alias ...="cd ../.."
alias ...="cd ../../.."
alias ....="cd ../../../.."
alias .....="cd ../../../../.."
alias ......="cd ../../../../../.."
alias ~="cd ~"
#alias --="cd -"

# listing
alias lsnice='ls -lhaG' 

# Using gpg via homebrew
# but it has a funky name, contemplating alias
# alias gpg=gnupg
alias gpg2=gnupg

# tar 
alias untar='tar -zxvf '

# wget 
# allows resume if something goes wrong, seems 
# good default behavior :)
alias wget='wget -c '

# random password generation (20 chars)
alias getpass='openssl rand -base64 20'

# sha test file 
alias sha='shasum -a 256'

# ping goes on forever, pingcount <num> will ping 5,10,15,etc
alias pingcount='ping -c '

# IP address 
alias machineip='ipconfig getifaddr en0'
alias myip='machineip'