#!/bin/bash

# make reloading settings a bit simpler
alias reload='source ~/.bash_profile'

# directory traversal, up 'n' folders
alias ..="cd .."
alias ...="cd ../.."
alias ...="cd ../../.."
alias ....="cd ../../../.."
alias .....="cd ../../../../.."
alias ......="cd ../../../../../.."
alias ~="cd ~"
#alias --="cd -"

# listing
alias lsnice='ls -lhaG' 

# git
# glg provides git log, with colors
# TODO: put this in my gitconfig, shouldn't depend on whatever shell....
alias gst='git status'
alias gco='git checkout'
alias gci='git commit'
alias grb='git rebase'
alias gbr='git branch'
alias gad='git add -A'
alias gpl='git pull'
alias gpu='git push'
alias glg='git log --date-order --all --graph --format="%C(green)%h%Creset %C(yellow)%an%Creset %C(blue bold)%ar%Creset %C(red bold)%d%Creset%s"'
