#!/bin/bash 

# some helpful posts:
# http://blog.taylormcgann.com/tag/prompt-color/
# https://gist.github.com/elucify/c7ccfee9f13b42f11f81

# Regular Colors
# \[\033[0;30m\] # Black
# \[\033[0;31m\] # Red
# \[\033[0;32m\] # Green
# \[\033[0;33m\] # Yellow
# \[\033[0;34m\] # Blue
# \[\033[0;35m\] # Purple
# \[\033[0;36m\] # Cyan
# \[\033[0;37m\] # White

# # High Intensty
# \[\033[0;90m\] # Black
# \[\033[0;91m\] # Red
# \[\033[0;92m\] # Green
# \[\033[0;93m\] # Yellow
# \[\033[0;94m\] # Blue
# \[\033[0;95m\] # Purple
# \[\033[0;96m\] # Cyan
# \[\033[0;97m\] # White

# # Background
# \[\033[40m\] # Black
# \[\033[41m\] # Red
# \[\033[42m\] # Green
# \[\033[43m\] # Yellow
# \[\033[44m\] # Blue
# \[\033[45m\] # Purple
# \[\033[46m\] # Cyan
# \[\033[47m\] # White

# # High Intensty backgrounds
# \[\033[0;100m\] # Black
# \[\033[0;101m\] # Red
# \[\033[0;102m\] # Green
# \[\033[0;103m\] # Yellow
# \[\033[0;104m\] # Blue
# \[\033[10;95m\] # Purple
# \[\033[0;106m\] # Cyan
# \[\033[0;107m\] # White

# #Replace any leading leading 0; with 1; for bold colors
# #Replace any leading 0; with 4; to underline

# set in some variables:
RESTORE=$(echo -en '\033[0m')
RED=$(echo -en '\033[00;31m')
GREEN=$(echo -en '\033[00;32m')
YELLOW=$(echo -en '\033[00;33m')
BLUE=$(echo -en '\033[00;34m')
MAGENTA=$(echo -en '\033[00;35m')
PURPLE=$(echo -en '\033[00;35m')
CYAN=$(echo -en '\033[00;36m')
LIGHTGRAY=$(echo -en '\033[00;37m')
LRED=$(echo -en '\033[01;31m')
LGREEN=$(echo -en '\033[01;32m')
LYELLOW=$(echo -en '\033[01;33m')
LBLUE=$(echo -en '\033[01;34m')
LMAGENTA=$(echo -en '\033[01;35m')
LPURPLE=$(echo -en '\033[01;35m')
LCYAN=$(echo -en '\033[01;36m')
WHITE=$(echo -en '\033[01;37m')

# # Test
# echo ${RED}RED${GREEN}GREEN${YELLOW}YELLOW${BLUE}BLUE${PURPLE}PURPLE${CYAN}CYAN${WHITE}WHITE${RESTORE}
alias colors="echo ${RED}RED${GREEN}GREEN${YELLOW}YELLOW${BLUE}BLUE${PURPLE}PURPLE${CYAN}CYAN${WHITE}WHITE${RESTORE}"