#!/bin/bash 

# see: https://github.com/holman/dotfiles/blob/80b2bd57e9c594dc7c783989801ee51930068d59/zsh/config.zsh
# for more nuggets....
export HISTSIZE=50000
export HISTFILESIZE=50000
export HISTTIMEFORMAT="%d/%m/%y %T "
# when exit, append rather than overwrite
shopt -s histappend

# # After each command, append to the history file and reread it
# export PROMPT_COMMAND="${PROMPT_COMMAND:+$PROMPT_COMMAND$'\n'}history -a; history -c; history -r"
reload_history() {
    history -a 
    history -c 
    history -r
}