#!/bin/bash 

# see: https://github.com/holman/dotfiles/blob/80b2bd57e9c594dc7c783989801ee51930068d59/zsh/config.zsh
# and: https://gist.github.com/ckabalan/7d374ceea8c2d9dd237d763d385cf2aa
#
# /etc/profile.d/best_bash_history.sh
# Save 5,000 lines of history in memory
HISTSIZE=10000
# Save 2,000,000 lines of history to disk (will have to grep ~/.bash_history for full listing)
HISTFILESIZE=2000000
# Append to history instead of overwrite
shopt -s histappend
# Ignore redundant or space commands
HISTCONTROL=ignoreboth
# Ignore more
HISTIGNORE='ls:ll:ls -alh:pwd:clear:history'
# Set time format
HISTTIMEFORMAT='%F %T '
# Multiple commands on one line show up as a single line
shopt -s cmdhist

# # After each command, append to the history file and reread it
# export PROMPT_COMMAND="${PROMPT_COMMAND:+$PROMPT_COMMAND$'\n'}history -a; history -c; history -r"
# 
# Append new history lines, clear the history list, re-read the history list, print prompt.
# export PROMPT_COMMAND="history -a; history -c; history -r; $PROMPT_COMMAND"
reload_history() {
    history -a; history -c; history -r
}